  spring:
    security:
      oauth2:
        client:
          registration:
            github:
              client-id: ${CLIENT_ID}
              client-secret: ${CLIENT_SECRET}
    data:
      cassandra:
        keyspace-name: main
        username: ${USERNAME_DB}
        password: ${PASSWORD_DB}
        schema-action: create_if_not_exists
        request:
          timeout: 10s
        connection:
          connect-timeout: 10s
          init-query-timeout: 10s

  datastax.astra:
    secure-connect-bundle: secure-connect.zip


  astra.db:
    id: ${DB_ID}
    region: eu-central-1
    keyspace: main
    application.token: ${TOKEN_DB}





